### ISSUE TITLE
1.1.x do not work when deployed to Windows

### ISSUE THREAD

**Issue by anthonychu** [anthonychu/azure-functions-deno-worker#13] opened 2020-06-20 06:20 UTC
Getting an error when deployed to Windows consumption plan. Downgrading to `1.0.5` works fine.

![image](https://user-images.githubusercontent.com/3982077/85194863-5da86b80-b283-11ea-8ede-901d3be05504.png)

@horihiro Are you seeing the same?

**Comment by horihiro** [comment] 2020-06-20 06:56
Yes, I can reproduce it.😕

**Comment by horihiro** [comment] 2020-06-20 07:26
There are following logs in log file @ `D:\home\LogFiles\Application\Functions\Host`

```
2020-06-20T07:11:35.484 [Information] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 6, kind: Other, message: "The handle is invalid." }', cli\ops\io.rs:86:17
2020-06-20T07:11:35.485 [Information] stack backtrace:
2020-06-20T07:11:35.551 [Information] 0:     0x7ff7554d176f - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.551 [Information] 1:     0x7ff7554f31bb - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.551 [Information] 2:     0x7ff7554c732c - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.551 [Information] 3:     0x7ff7554d4ccc - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.551 [Information] 4:     0x7ff7554d490f - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.551 [Information] 5:     0x7ff7554d54b7 - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.552 [Information] 6:     0x7ff7554d503f - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.552 [Information] 7:     0x7ff7554f1b10 - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.553 [Information] 8:     0x7ff7554f1963 - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.553 [Information] 9:     0x7ff753f0c616 - <unknown>
2020-06-20T07:11:35.553 [Information] 10:     0x7ff754122eca - <unknown>
2020-06-20T07:11:35.553 [Information] 11:     0x7ff753ec4c83 - <unknown>
2020-06-20T07:11:35.553 [Information] 12:     0x7ff753e6949e - <unknown>
2020-06-20T07:11:35.553 [Information] 13:     0x7ff753f7bf69 - <unknown>
2020-06-20T07:11:35.554 [Information] 14:     0x7ff753eb2724 - <unknown>
2020-06-20T07:11:35.554 [Information] 15:     0x7ff753ffc125 - <unknown>
2020-06-20T07:11:35.554 [Information] 16:     0x7ff753f57160 - <unknown>
2020-06-20T07:11:35.554 [Information] 17:     0x7ff7540e9326 - <unknown>
2020-06-20T07:11:35.554 [Information] 18:     0x7ff7554d56ca - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.559 [Information] 19:     0x7ff753f5b027 - <unknown>
2020-06-20T07:11:35.559 [Information] 20:     0x7ff755503df0 - CrashForExceptionInNonABICompliantCodeRange
2020-06-20T07:11:35.559 [Information] 21:     0x7fff7e5a84d4 - BaseThreadInitThunk
2020-06-20T07:11:35.582 [Information] 22:     0x7fff80cae8b1 - RtlUserThreadStart
```

And `cli\ops\io.rs:86:17`, which is pointed at above log, was changed in https://github.com/denoland/deno/pull/6126 

https://github.com/denoland/deno/releases/tag/v1.1.0
![image](https://user-images.githubusercontent.com/4566555/85195991-09000180-b312-11ea-8c11-f305d35b1a33.png)


https://github.com/denoland/deno/commit/1e0808d501cf9adea65e7cacd123ea4fea06a13a#diff-52a4a7cdf78afa52dbd3506067839baaL74-R88

It seems that the change is related to this issue...🤔

**Comment by horihiro** [comment] 2020-06-20 07:30
Additionally, `std` was upgraded, latest is 0.58.0 though I'm not sure that the upgrade is related to this issue...

**Comment by horihiro** [comment] 2020-06-20 08:15
I'm confused because following command can be executed on Kudu console.
![image](https://user-images.githubusercontent.com/4566555/85196965-d3aae200-b318-11ea-99fa-c9f4e1044228.png)
The command was failed in the above log.

And the deno process on Kudu seems to work fine.
![image](https://user-images.githubusercontent.com/4566555/85196975-eb826600-b318-11ea-9887-bc58c29de3f1.png)

I cannot understand that only Kudu can execute the command.

**Comment by horihiro** [comment] 2020-06-20 09:36
My current hypothesis is:

  - When launching deno as HttpWorker, stdin is not enabled, because there is no `RedirectStandardInput` at [DefaultWorkerProcessFactory on Function Host](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Workers/ProcessManagement/DefaultWorkerProcessFactory.cs#L42-L48)

    https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.redirectstandardinput?view=netcore-3.1#System_Diagnostics_ProcessStartInfo_RedirectStandardInput

  - Then deno cannot get stdin handle at [this](https://github.com/caspervonb/deno/blob/master/cli/ops/io.rs#L44-L48).

This is just a hypothesis, debugging of deno and/or function host may be needed in order to prove this.

**Comment by horihiro** [comment] 2020-06-20 12:25
This issue can be reproduced on Windows Web App and simple asp net core app which invokes deno process by [same way as function host](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Workers/ProcessManagement/DefaultWorkerProcessFactory.cs#L26).

And I confirmed that it could be avoided this by adding `RedirectStandardInput = true,` to `ProcessStartInfo`'s constructor as following in the simple aspnetcore app.

```C#
            var startInfo = new ProcessStartInfo(@"PATH\TO\deno.exe")
            {
                RedirectStandardInput = true,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                // : others
            };
```

**Comment by anthonychu** [comment] 2020-06-20 16:07
Thanks for finding the problem!

Does it only happen on Windows Azure Functions / App Service? It’s working fine locally on Windows, right?

Let me know if there’s a workaround that we can implement in the Deno worker to fix it.

It sounds like this should be fixed in both the runtime and in Deno.

Can you please create an issue on https://github.com/Azure/azure-functions-host/issues to discuss? Thanks!

/cc @pragnagopa

**Comment by pragnagopa** [comment] 2020-06-20 17:50
Azure Functions should not require interactive inputs. This is by design that `RedirectStandardInput` is not set to `true`.

This should be tracked in deno repo.  Launching `deno.exe` should not require enabling std input.

**Comment by horihiro** [comment] 2020-06-20 22:00
Thank you for the comment @anthonychu  and @pragnagopa ,

Please let me clarify the condition this issue happens.
After that I will create an issue on deno repo.

**Comment by horihiro** [comment] 2020-06-22 22:09
Hmm, I cannot reproduce this on  local IIS 10 ( on Win10) and the aspnetcore app, or console app.

The environment I can reproduce this is only on App Service.
So it might be hard to debug on `deno` side.

@anthonychu and @pragnagopa 
Do you have any idea to reproduce on local PC?

**Comment by pragnagopa** [comment] 2020-06-23 00:58
Did you try running the function locally using core tools: https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Ccsharp%2Cbash ?

**Comment by horihiro** [comment] 2020-06-23 01:25
Thanks Pragna for reply,

Yes I tried `func` command locally and it works.

As long as I know, this is only happened when `deno` is invoked by `Process#Start` with the `ProcessStartInfo` without `RedirectStandardInpit = true` on App Service.

**Comment by horihiro** [comment] 2020-06-23 05:43
I sent PR for workaround to avoid this issue.
\# This also is hacky a little...

**Comment by horihiro** [comment] 2020-06-28 00:08
This issue will be fixed by https://github.com/denoland/deno/pull/6528
So next release ( v1.1.3 ) or later of deno will be able to work without any change on `denofunc` probably.

**Comment by horihiro** [comment] 2021-07-31 22:41
This issue is already fixed.

**Closed by horihiro** 2021-07-31 22:41 UTC
